# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.csv_reader_filter:
        class:        AppBundle\Service\CsvReaderFilter
        arguments:    [ "%product.headers%", "@validator" ]

    app.logger:
            class:        AppBundle\Service\Logger
            arguments:    [  ]

    app.csv_validator:
            class:        AppBundle\Service\CsvValidator
            arguments:    [ "%product.headers%" ]
