# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.csv_parser:
        class:        AppBundle\Service\CsvParser
        arguments:    [ ]

    app.alter_entities:
            class:        AppBundle\Service\AlterEntities
            arguments:    [ '@doctrine.orm.entity_manager' ]

    app.logger:
            class:        AppBundle\Service\Logger
            arguments:    [  ]

    app.validator:
            class:        AppBundle\Service\Validator
            arguments:    [  ]
